version: '3.8'

services:
  postgres:
    container_name: postgres_db
    image: postgres
    restart: always
    volumes:
      - ./data/db:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=test
    ports:
      - 5432:532
    networks:
      app_net:
        ipv4_address: 192.168.0.2

  pg_admin:
    container_name: pg_admin
    image: dpage/pgadmin4
    restart: always
    volumes:
      - ./data/pg_admin:/var/lib/pgadmin
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@gmail.com
      - PGADMIN_DEFAULT_PASSWORD=password
    ports:
      - 8080:80
    networks:
      app_net:
        ipv4_address: 192.168.0.3

networks:
  app_net:
    ipam:
      driver: default
      config:
        - subnet: 192.168.0.0/24
          gateway: 192.168.0.1